name: Insert meta into index.html

on:
  workflow_dispatch:

  push:
    tags:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}


      - name: Update index
        run: |
          sed -i '1i HI />' public/index.html
          git config --global user.email "heng.zhang@cloudfall.cn" && git config --global user.name "GitHub Action"
          git add . && git commit -m "update package.json" && git push origin HEAD:main

      - name: Insert meta
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          sed -i '4i <meta name="version" content="${{ github.ref_name }}" />' public/index.html
          cat public/index.html
